"""Add recovery actions

Revision ID: 4fa29c526aba
Revises: b6d3164b8819
Create Date: 2026-08-26 19:30:15.638307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa29c526aba'
down_revision: Union[str, Sequence[str], None] = 'b6d3164b8819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('agent_decision_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('external_reference', sa.String(length=200), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_decision_id'], ['agent_decisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_action_type'), 'recovery_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_recovery_actions_agent_decision_id'), 'recovery_actions', ['agent_decision_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_external_reference'), 'recovery_actions', ['external_reference'], unique=False)
    op.create_index(op.f('ix_recovery_actions_recovery_case_id'), 'recovery_actions', ['recovery_case_id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_status'), 'recovery_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_status'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_recovery_case_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_external_reference'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_agent_decision_id'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_action_type'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    # ### end Alembic commands ###
