"""Add recovery cases

Revision ID: 8edba4656ed2
Revises: c74511d692ee
Create Date: 2026-08-26 19:16:46.260349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edba4656ed2'
down_revision: Union[str, Sequence[str], None] = 'c74511d692ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('failure_class', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_customer_id'), 'recovery_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_failure_class'), 'recovery_cases', ['failure_class'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_cases_transaction_id'), 'recovery_cases', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_cases_transaction_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_failure_class'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_customer_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    # ### end Alembic commands ###
