"""Add agent decisions

Revision ID: b6d3164b8819
Revises: 8edba4656ed2
Create Date: 2026-08-26 19:22:24.210451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d3164b8819'
down_revision: Union[str, Sequence[str], None] = '8edba4656ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reasoning_summary', sa.String(length=1000), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expected_recovery_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('policy_status', sa.String(length=30), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_decision'), 'agent_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_agent_decisions_policy_status'), 'agent_decisions', ['policy_status'], unique=False)
    op.create_index(op.f('ix_agent_decisions_recovery_case_id'), 'agent_decisions', ['recovery_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_decisions_recovery_case_id'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_policy_status'), table_name='agent_decisions')
    op.drop_index(op.f('ix_agent_decisions_decision'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
